config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'find_administrative_division', to: 'country_state#find_administrative_divisions'
  get 'find_city', to: 'country_state#find_cities'
  resources :profiles, only: [:show, :edit, :update] do
    resources :psa_histories, only: [:index]
    resources :cholesterol_histories, only: [:index]
    resources :medications, only: [:index]
  end
  resources :topics, only: [:create, :new, :index, :show] do
    resources :posts, except: [:index, :destroy] do
      member do
        put :delete
      end
      resources :comments, except: [:index, :destroy] do
        member do
          put :delete
        end
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent_comment, class_name: 'Comment', foreign_key: 'parent_comment_id', optional: true
  has_many :child_comments, class_name: 'Comment', foreign_key: 'parent_comment_id'

  validates :content, presence: true, length: { maximum: 40_000 }
  validates :user_id, presence: true
  validates :post_id, presence: true

  def get_ancestors_count(comment)
    @ancestors ||= 0

    return @ancestors if comment.parent_comment.nil?
    @ancestors += 1
    get_ancestors_count(comment.parent_comment)
  end

  def get_children_tree(comment, depth)
    @children_tree ||= []

    comment.child_comments.each do |child_comment|
      return @children_tree if (child_comment.ancestor_count - @root.ancestor_count) > depth
      @children_tree << child_comment
      get_children_tree(child_comment, depth)
    end
    @children_tree
  end

  def ancestor_count
    @ancestors ||= get_ancestors_count(self)
  end

  def children_tree(depth)
    @root = self
    @children_tree ||= get_children_tree(self, depth)
  end

  def hidden_replies?(ancestor, depth)
    (ancestor_count - ancestor.ancestor_count) >= depth && !child_comments.empty?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include UserAccess
  before_action :authenticate_user!, except: [:show]
  before_action :set_comment, only: [:edit, :show, :update, :delete]
  before_action only: [:edit, :update, :delete] { require_same_user(@comment) }
  before_action :check_deleted, only: [:edit, :update, :delete]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:success] = 'Your comment has been successfully created'
      redirect_to topic_post_comment_path(@post.topic, @post, @comment)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:success] = 'Comment has been updated'
      redirect_to topic_post_comment_path(@comment)
    else
      render 'edit'
    end
  end

  def show
    @post = @comment.post
  end

  def delete
    @comment.content = '[deleted]'
    @comment.deleted = true
    @comment.save
    flash[:danger] = 'Your comment has been successfully deleted'
    redirect_to topic_post_comment_path(@comment)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def check_deleted
    return unless @comment.deleted?
    flash[:danger] = 'This comment is deleted'
    redirect_to topic_post_comment_path(@comment)
  end
end

app/views/comments/_comment.html.erb
<% if @comment && @comment.parent_comment %>
  <div class='comment margin-level-<%= comment.ancestor_count - @comment.parent_comment.ancestor_count %>'>
<% else %>
  <div class='comment margin-level-<%= comment.ancestor_count %>'>
<% end %>
  <p class='forum-information'>
    <%= link_to comment.user.username, profile_path(comment.user.profile) %> -
    <%= time_ago_in_words(comment.created_at) %> ago
  </p>
  <%= markdown(comment.content) %>
  <%= link_to 'Reply to Comment', new_topic_post_comment_path(@post.topic, @post, :parent_comment_id => comment.id),
                                  class: 'btn btn-primary btn-xs' %>
  <% if comment.user == current_user && !comment.deleted %>
    <%= link_to 'edit comment', edit_topic_post_comment_path(@post.topic, @post, comment),
                                class: 'btn btn-info btn-xs' %>
    <%= link_to 'delete comment', delete_topic_post_comment_path(@post.topic, @post, comment),
                                  method: :put, data: { confirm: 'Are you sure?' },
                                  class: 'btn btn-danger btn-xs' %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= render 'shared/errors', obj: @comment %>
<%= form_for([@topic, @post, @comment], url: url) do |f| %>
  <%= f.hidden_field(:parent_comment_id, :value => params[:parent_comment_id]) %>
  <div class='form-group'>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<div>
  <%= comment.content %>
  <%= link_to "Reply to Comment", new_topic_post_comment_path(@post.topic, @post, :parent_comment_id => comment.id), 
                                  class: "btn btn-primary btn-xs" %>
  <% if comment.user == current_user && !comment.deleted %>
    <%= link_to "edit comment", edit_topic_post_comment_path(@post.topic, @post, comment), 
                                class: "btn btn-primary btn-xs" %>
    <%= link_to "delete comment", delete_topic_post_comment_path(@post.topic, @post, comment),
                                  method: :patch, data: { confirm: "Are you sure?" },
                                  class: "btn btn-primary btn-xs" %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h2>Edit Your Comment</h2>
<%= render 'form', url: topic_post_comment_path(@comment) %>

app/views/comments/new.html.erb
<h2>Create a new Comment</h2>
<%= render 'form', url: topic_post_comments_path %>

app/views/comments/show.html.erb
<%= render '/posts/show' %>