config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'find_administrative_division', to: 'country_state#find_administrative_divisions'
  get 'find_city', to: 'country_state#find_cities'
  resources :profiles, only: [:show, :edit, :update] do
    resources :psa_histories, only: [:index]
    resources :cholesterol_histories, only: [:index]
    resources :medications, only: [:index]
  end
  resources :topics, only: [:create, :new, :index, :show] do
    resources :posts, except: [:index, :destroy] do
      member do
        put :delete
      end
      resources :comments, except: [:index, :destroy] do
        member do
          put :delete
        end
      end
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts

  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include UserAccess
  before_action :require_admin, except: [:show, :index]

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.order(created_at: :desc).paginate(page: params[:page], per_page: 30)
  end

  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      flash[:success] = 'A new topic has been successfully created'
      redirect_to topics_path
    else
      render 'new'
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/views/topics/index.html.erb
<% @topics.each do |topic| %>
  <div class='topic'>
    <h2><%= link_to topic.name, topic_path(topic) %></h2>
    <p><%= pluralize(topic.posts.count, 'post') %></p>
    <% unless topic.posts.empty? %>
      <p>
        last post: <%= link_to topic.posts.last.title, topic_post_path(topic, topic.posts.last) %>
        by <%= link_to topic.posts.last.user.username, profile_path(topic.posts.last.user.profile) %>
        <%= time_ago_in_words(topic.posts.last.created_at) %> ago
      </p>
    <% end %>
  </div>
<% end %>

<% if current_user.try(:admin?) %>
  <%= link_to 'New Topic', new_topic_path, class: 'btn btn-primary' %>
<% end %>

app/views/topics/new.html.erb
<%= render 'shared/errors', obj: @topic %>
<%= form_for(@topic) do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% unless @topic.posts.blank? %>
  <% @posts.each do |post| %>
    <% unless post.deleted? %>
      <%= render(post) %>
    <% end %>
  <% end %>
  <%= will_paginate(@posts) %>
<% else %>
  <p>There are no posts under this topic</p>
<% end %>

<%= link_to 'New Post', new_topic_post_path(@topic), class: 'btn btn-primary' %>