config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'find_administrative_division', to: 'country_state#find_administrative_divisions'
  get 'find_city', to: 'country_state#find_cities'
  resources :profiles, only: [:show, :edit, :update] do
    resources :psa_histories, only: [:index]
    resources :cholesterol_histories, only: [:index]
    resources :medications, only: [:index]
  end
  resources :topics, only: [:create, :new, :index, :show] do
    resources :posts, except: [:index, :destroy] do
      member do
        put :delete
      end
      resources :comments, except: [:index, :destroy] do
        member do
          put :delete
        end
      end
    end
  end
end

app/views/shared/_dashboard.html.erb
<aside id='dashboard'>
  <ul>
    <% if @profile.empty? %>
      <li>
        <%= link_to 'Create Your Profile', edit_profile_path(@profile) %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Edit Your Profile', edit_profile_path(@profile) %>
      </li>
      <li>
        <%= link_to 'PSA History', profile_psa_histories_path(@profile) %>
        </li>
      <li>
        <%= link_to 'Cholesterol History', profile_cholesterol_histories_path(@profile) %>
      </li>
      <li>
        <%= link_to 'Medications', profile_medications_path(@profile) %>
      </li>
    <% end %>
  </ul>
</aside>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='panel panel-danger'>
    <div class='panel-heading'>
      <h2 class='panel-title'>
        <%= pluralize(obj.errors.count, 'error') %>
        prohibited this record from being saved:
      </h2>
      <div class='panel-body'>
        <u1>
          <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </u1>
      </div>
    </div>
  </div>
<% end %>