config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'find_administrative_division', to: 'country_state#find_administrative_divisions'
  get 'find_city', to: 'country_state#find_cities'
  resources :profiles, only: [:show, :edit, :update] do
    resources :psa_histories, only: [:index]
    resources :cholesterol_histories, only: [:index]
    resources :medications, only: [:index]
  end
  resources :topics, only: [:create, :new, :index, :show] do
    resources :posts, except: [:index, :destroy] do
      member do
        put :delete
      end
      resources :comments, except: [:index, :destroy] do
        member do
          put :delete
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :comments

  validates :title, presence: true, length: { maximum: 200 }
  validates :content, presence: true, length: { maximum: 40_000 }
  validates :user_id, presence: true
  validates :topic_id, presence: true

  def direct_replies
    comments.select { |comment| comment.parent_comment.nil? }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!, except: [:show]
  before_action :set_post, only: [:edit, :show, :update, :delete]
  before_action :require_same_user, only: [:edit, :update, :delete]
  before_action :check_deleted, only: [:edit, :update, :delete]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @topic = Topic.find(params[:topic_id])
    @post.user = current_user
    @post.topic = @topic
    if @post.save
      flash[:success] = 'Your post has been successfully created'
      redirect_to topic_post_path(@topic, @post)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:success] = 'Post has been updated'
      redirect_to topic_post_path(@post)
    else
      render 'edit'
    end
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def delete
    @post.title = '[deleted]'
    @post.content = '[deleted]'
    @post.deleted = true
    @post.save
    flash[:danger] = 'Your post has been successfully deleted'
    redirect_to topic_post_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_same_user
    return if current_user == @post.user
    flash[:danger] = 'You can only edit or delete your own content'
    redirect_to topic_post_path(@post)
  end

  def check_deleted
    return unless @post.deleted?
    flash[:danger] = 'This post is deleted'
    redirect_to topic_post_path(@post)
  end
end

app/views/posts/_content.html.erb
<div class='content'>
  <%= markdown(@post.content) %>
</div>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>
<%= form_for([@topic, @post], url: url) do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>
    

app/views/posts/_post.html.erb
<div class='post'>
  <h2><%= link_to post.title, topic_post_path(post.topic, post) %></h2>
  <p class='forum-information'><%= pluralize(post.comments.count, 'comment') %></p>
  <p class='forum-information'>
    created <%= time_ago_in_words(post.created_at) %> ago by
    <%= link_to post.user.username, profile_path(post.user.profile) %>
  </p>
  <% if @topic %>
    <%= link_to 'expand', topic_post_path(@topic, post), remote: true, class: 'btn btn-default' %>
  <% else %>
    <%= render 'posts/content' %>
    <%= link_to 'reply to post', new_topic_post_comment_path(@post.topic, @post), class: 'btn btn-primary btn-xs' %>
    <% if @post.user == current_user && !@post.deleted? %>
      <%= link_to 'edit post', edit_topic_post_path(@post.topic, @post), class: 'btn btn-info btn-xs' %>
      <%= link_to 'delete post', delete_topic_post_path(@post.topic, @post),
                                 method: :put, data: { confirm: 'Are you sure?' },
                                 class: 'btn btn-danger btn-xs' %>
    <% end %>
  <% end %>
</div>

app/views/posts/_show.html.erb
<h1><%= link_to @post.topic.name, topic_path(@post.topic) %></h1>

<%= render(@post) %>

<% if @comment %>
  <% if @comment.parent_comment %>
    <%= render(@comment.parent_comment) %>
  <% end %>
  <div class='highlight'>
    <%= render(@comment) %>
  </div>
  <% @comment.children_tree(4).each do |child_comment| %>
    <%= render(child_comment) %>
    <% if child_comment.hidden_replies?(@comment, 4) %>
      <%= link_to 'see additional replies', topic_post_comment_path(@post.topic, @post, child_comment), class: 'margin-level-5' %>
    <% end %>
  <% end %>
<% else %>
  <% @post.direct_replies.each do |comment| %>
    <%= render(comment) %>
    <% comment.children_tree(5).each do |child_comment| %>
      <%= render(child_comment) %>
      <% if child_comment.hidden_replies?(comment, 5) %>
        <%= link_to 'see additional replies', topic_post_comment_path(@post.topic, @post, child_comment), class: 'margin-level-5' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Your Post</h2>
<%= render 'form', url: topic_post_path(@post) %>

app/views/posts/new.html.erb
<h2>Create a new Post</h2>
<%= render 'form', url: topic_posts_path %>

app/views/posts/show.html.erb
<%= render 'show' %>

app/views/posts/show.js.erb
/*global $*/
var expandElement = $("a[data-remote='true'][href='/topics/<%= @post.topic.id %>/posts/<%= @post.id %>']");
var postDiv = expandElement.parent();
var collapseElementHTML = '<button class="btn btn-default">collapse</button>';
postDiv.append("<%=j render 'content' %>");
expandElement.replaceWith(collapseElementHTML);

var collapseElement = postDiv.children('button:first');
collapseElement.on("click", function() {
  collapseElement = $(this);
  var contentDiv = collapseElement.siblings('div:first');
  contentDiv.toggle();
  if (collapseElement.text() === "collapse") {
    collapseElement.html("expand");
  } else {
    collapseElement.html("collapse");
  }
});